### ISSUE TITLE
Unexpexted results in response.

### ISSUE THREAD

**Issue by ProgrammerIgor** [barseghyanartur/django-elasticsearch-dsl-drf#147]
Hi. I can't figure out what I do improperly. 
**documents.py**

```python
@registry.register_document
class ColourDocument(Document):
    name = fields.StringField(
        fields={
            'raw': fields.StringField(analyzer=html_strip),
            'suggest': fields.CompletionField()
        }
    )

    class Index:
        name = 'colour'
        settings = {
            'number_of_shards': 1,
            'number_of_replicas': 0
        }

    class Django:
        model = Colour
        ignore_signals = False
        auto_refresh = True
        queryset_pagination = 20

    def get_queryset(self):
        return super(ColourDocument, self).get_queryset().select_related('animal').order_by('name')
```

**serializers.py**

```python
class ColourDocumentSerializer(DocumentSerializer):
    class Meta:
        document = ColourDocument

        fields = (
            'name',
        )
```
**views.py**

```python
class ColourDocumentView(DocumentViewSet):
    document = ColourDocument
    serializer_class = ColourDocumentSerializer
    pagination_class = None
    filter_backends = [
        SuggesterFilterBackend
    ]

    suggester_fields = {
        'name_suggest': {
            'field': 'name.suggest',
            'suggesters': [
                SUGGESTER_COMPLETION,
            ],
            'options': {
                'size': 20,
            },
        }
    }

    def filter_queryset(self, queryset):
        self.action = 'suggest'
        return super().filter_queryset(queryset)
```

I use elasticsearch with docker (docker.elastic.co/elasticsearch/elasticsearch:6.4.2).

When I try to perform this:
`GET http://0.0.0.0:8000/v1/colours/search/?name_suggest__completion=wh`
I get the first 10  color items without any filtration.

**Comment by ProgrammerIgor** [comment]
When I try to perform this request:
`GET http://0.0.0.0:9200/colour/doc/_count` with body
```json
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
             "id": "name_suggest__completion=white"
          }
        }
      ]
    }
  }
}
```

I get this:
```json
{
  "count": 0,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  }
}
```

**Comment by barseghyanartur** [comment]
@ProgrammerIgor:

Did you configure your pagination properly? This is essential. Search the docs.

**Comment by ProgrammerIgor** [comment]
When I change pagination class in my view
`pagination_class = PageNumberPagination`
I get this error:
```app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
app_1            |     response = get_response(request)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
app_1            |     response = self.process_exception_by_middleware(e, request)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
app_1            |     return view_func(*args, **kwargs)
app_1            |   File "/pet4you_backend/rest_framework/viewsets.py", line 116, in view
app_1            |     return self.dispatch(request, *args, **kwargs)
app_1            |   File "/pet4you_backend/rest_framework/views.py", line 495, in dispatch
app_1            |     response = self.handle_exception(exc)
app_1            |   File "/pet4you_backend/rest_framework/views.py", line 455, in handle_exception
app_1            |     self.raise_uncaught_exception(exc)
app_1            |   File "/pet4you_backend/rest_framework/views.py", line 492, in dispatch
app_1            |     response = handler(request, *args, **kwargs)
app_1            |   File "/pet4you_backend/rest_framework/mixins.py", line 45, in list
app_1            |     return self.get_paginated_response(serializer.data)
app_1            |   File "/pet4you_backend/rest_framework/serializers.py", line 765, in data
app_1            |     ret = super(ListSerializer, self).data
app_1            |   File "/pet4you_backend/rest_framework/serializers.py", line 262, in data
app_1            |     self._data = self.to_representation(self.instance)
app_1            |   File "/pet4you_backend/rest_framework/serializers.py", line 683, in to_representation
app_1            |     self.child.to_representation(item) for item in iterable
app_1            |   File "/pet4you_backend/rest_framework/serializers.py", line 683, in <listcomp>
app_1            |     self.child.to_representation(item) for item in iterable
app_1            |   File "/pet4you_backend/rest_framework/serializers.py", line 514, in to_representation
app_1            |     attribute = field.get_attribute(instance)
app_1            |   File "/pet4you_backend/rest_framework/fields.py", line 475, in get_attribute
app_1            |     raise type(exc)(msg)
app_1            | AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `ColourDocumentSerializer`.
app_1            | The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
app_1            | Original exception text was: 'str' object has no attribute 'name'.
```

**Comment by barseghyanartur** [comment]
Could you post your project somewhere? I think you have misconfigured something.

**Comment by ProgrammerIgor** [comment]
@barseghyanartur https://bitbucket.org/nocl1p/pet4you_backend/src/master/

**Comment by ProgrammerIgor** [comment]
@barseghyanartur have you looked through the project? I still can't figure out this problem.

**Comment by ProgrammerIgor** [comment]
So, I think that I'll figure out my problem by using Elasticsearch API directly. I don't need some sophisticated search designs, only autocomplete for several models.
