### ISSUE TITLE
ModuleNotFoundError: No module named 'debug_toolbar_force'

### ISSUE THREAD

**Issue by adl-asi** [barseghyanartur/django-elasticsearch-dsl-drf#200]
**Describe the bug**
Adding 'debug_toolbar_force.middleware.ForceDebugToolbarMiddleware' to MIDDLEWARE setting raises an error

**To Reproduce**
MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'debug_toolbar_force.middleware.ForceDebugToolbarMiddleware',
        ...
    ]

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by adl-asi** [comment]
Will add that there is a workaround if django-debug-toolbar-request-history is installed. Can select the elastic query from history, then the elastic panel will populate with the query

**Comment by barseghyanartur** [comment]
Could you paste a full trace and all your software versions?

**Comment by adl-asi** [comment]
Django==3.0.2
djangorestframework==3.11.0
django-debug-toolbar==2.2
django-debug-toolbar-request-history==0.1.1
django-elasticsearch-debug-toolbar==2.0.0
django-elasticsearch-dsl-drf==0.20.8


`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/proj/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/proj/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/proj/proj/wsgi.py", line 13, in <module>
    from configurations.wsgi import get_wsgi_application  # noqa
  File "/proj/venv/lib/python3.8/site-packages/configurations/wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/proj/venv/lib/python3.8/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/proj/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/proj/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 35, in load_middleware
    middleware = import_string(middleware_path)
  File "/proj/venv/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'debug_toolbar_force'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/proj/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/proj/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/proj/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/proj/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/proj/venv/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'proj.wsgi.application' could not be loaded; Error importing module.`

**Comment by barseghyanartur** [comment]
@adl-asi:

OK, silly question: Did you install [django-debug-toolbar-force](https://pypi.org/project/django-debug-toolbar-force/) package?

**Comment by adl-asi** [comment]
no... i did not :( thanks
