### ISSUE TITLE
docker front end example - not able to create test data ?

### ISSUE THREAD

**Issue by average-everyman** [barseghyanartur/django-elasticsearch-dsl-drf#237]
hello I was following the instruction for the front-end example, but the following step falls over:
```
$ ./scripts/create_test_data.shTraceback (most recent call last):
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/Documents/workspace-git/test-searchkit-3/django-elasticsearch-dsl-drf/examples/logs/all.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/Documents/workspace-git/test-searchkit-3/django-elasticsearch-dsl-drf/examples/simple/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/home/username/miniconda3/envs/test-searchkit-3/lib/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'all_log'
```
is there additional step required? or some dependency missing?

**Comment by barseghyanartur** [comment]
Frontend example is extremely outdated.Could you run `./scripts/create_dirs.sh` before you run other scripts?
