### ISSUE TITLE
why DocumentViewSet does not working?

### ISSUE THREAD

**Issue by marlonmp** [barseghyanartur/django-elasticsearch-dsl-drf#306]
**Describe the bug**
```python
class BuscarDocumentosViewSet(DocumentViewSet):

    document = DocumentoDocument
    serializer_class = DocumentoBusquedaSerializer
    filter_backends = [SearchFilterBackend]
    search_fields = ('nombre', 'attachment.content', 'attachment.title')
```
I got this error when I make a request
```sh
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
   response = get_response(request)
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.9/site-packages/django_elasticsearch_dsl_drf/viewsets.py", line 171, in __init__
   super(BaseDocumentViewSet, self).__init__(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Environment**

Python environment:
1. `pip list`
```sh
Package                      Version
---------------------------- ---------
asgiref                      3.6.0
astroid                      2.11.7
async-timeout                4.0.2
certifi                      2022.12.7
charset-normalizer           2.0.12
click                        8.1.3
contextlib2                  21.6.0
dill                         0.3.6
Django                       3.2.16
django-cors-headers          3.13.0
django-elasticsearch-dsl     7.2.2
django-elasticsearch-dsl-drf 0.22.5
django-filter                2.4.0
django-model-utils           4.2.0
django-nine                  0.2.7
django-redis                 5.2.0
django-rest-choices          0.0.1
djangorestframework          3.12.4
djangorestframework-jwt      1.11.0
dparse                       0.6.2
drf-renderer-xlsx            0.4.1
elasticsearch                7.17.8
elasticsearch-dsl            7.4.0
et-xmlfile                   1.1.0
flake8                       4.0.1
idna                         3.4
isort                        4.3.4
lazy-object-proxy            1.9.0
mccabe                       0.6.1
openpyxl                     3.0.10
packaging                    23.0
Pillow                       9.0.1
pip                          22.3.1
platformdirs                 2.6.2
psycopg2                     2.8.4
psycopg2-binary              2.9.5
pycodestyle                  2.8.0
pyflakes                     2.4.0
PyJWT                        1.6.4
pylint                       2.13.0
python-dateutil              2.8.2
python-magic                 0.4.27
pytz                         2022.7
raven                        6.0.0
redis                        4.4.2
requests                     2.27.1
rest-condition               1.0.3
ruamel.yaml                  0.17.21
ruamel.yaml.clib             0.2.7
safety                       2.2.0
sentry-sdk                   1.5.4
setuptools                   58.1.0
six                          1.16.0
sqlparse                     0.4.3
toml                         0.10.2
tomli                        2.0.1
typing_extensions            4.4.0
urllib3                      1.26.14
wheel                        0.38.4
wrapt                        1.14.1
xlrd                         1.2.0
XlsxWriter                   1.3.7
```
2. `python --version`
```sh
Python 3.9.16
```

Which version of Elasticsearch are you using?
8.6.0

**Comment by barseghyanartur** [comment]
It was tested with Elasticsearch 7.x. Strange error. Last time tested just a [couple of weeks ago](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/actions/runs/3790035700/jobs/6444330475) against Python 3.9, Django 3.2 and Elasticsearch 7.x with no errors.

**Comment by barseghyanartur** [comment]
There might be an issue with the way you define URLs.

**Comment by marlonmp** [comment]
This is the urls.py file
```python
from django.urls import path

from apps.fichero import views

urlpatterns = [
    ...

    path('documentos/busqueda/', views.BuscarDocumentosViewSet,
         name='fichero-buscar-documentos-api'),
]

```

**Comment by barseghyanartur** [comment]
That's it. You should use routers. See the documentation examples as well as the project in the examples directory.
