### ISSUE TITLE
Not working with Django 2.0

### ISSUE THREAD

**Issue by Rigel772** [barseghyanartur/django-elasticsearch-dsl-drf#70]
Following  the introduction tutorial and getting this error:
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f43acb17f28>
Traceback (most recent call last):
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/oskar/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/storage/oskar/PROJECTS/sandbox/elasticsearch/src/elastic/elastic/urls.py", line 18, in <module>
    from search_indexes import urls as search_index_urls
  File "/media/storage/oskar/PROJECTS/sandbox/elasticsearch/src/elastic/search_indexes/urls.py", line 2, in <module>
    from rest_framework_extensions.routers import ExtendedDefaultRouter
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/rest_framework_extensions/routers.py", line 7, in <module>
    from rest_framework.routers import (
ImportError: cannot import name 'replace_methodname'

```
pip freeze:
```
astroid==2.0.1
Django==2.0.7
django-elasticsearch-dsl==0.5.0
django-elasticsearch-dsl-drf==0.13.1
django-nine==0.1.13
djangorestframework==3.8.2
drf-extensions==0.3.1
elasticsearch==6.3.0
elasticsearch-dsl==6.1.0
Faker==0.8.17
ipaddress==1.0.22
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
Pillow==5.2.0
psycopg2==2.7.5
pylint==2.0.1
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0
text-unidecode==1.2
typed-ast==1.1.0
urllib3==1.23
wrapt==1.10.11
```

**Comment by Rigel772** [comment]
Actually before I had this error:
```
File "/media/storage/oskar/PROJECTS/sandbox/elasticsearch/src/elastic/elastic/urls.py", line 18, in <module>
    from search_indexes import urls as search_index_urls
  File "/media/storage/oskar/PROJECTS/sandbox/elasticsearch/src/elastic/search_indexes/urls.py", line 2, in <module>
    from rest_framework_extensions.routers import ExtendedDefaultRouter
  File "/home/oskar/.virtualenvs/elastic_env/lib/python3.6/site-packages/rest_framework_extensions/routers.py", line 4, in <module>
    from django.core.urlresolvers import NoReverseMatch
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
so I tried to replace  in rest_framework_extensions/routers.py
`from django.core.urlresolvers import NoReverseMatch`
with
`from django.urls import NoReverseMatch`

**Comment by barseghyanartur** [comment]
@Rigel772:

I've updated the docs (not yet readthedocs, though). Thanks for pointing out at this.
